# Generated by Django 3.0.2 on 2020-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceText',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtext',
            field=models.CharField(max_length=200),
        ),
    ]
